
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use the actual Supabase project credentials
const SUPABASE_URL = 'https://lkvelwwrztkmnvgeknpa.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrdmVsd3dyenRrbW52Z2VrbnBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDU5MDksImV4cCI6MjA2NjI4MTkwOX0.FYncO6mPqw5mJr4ek8kQdgvdo15nXU42vqq-TUtwuts';

if (import.meta.env.DEV) {
  console.log('🔗 Initializing Supabase client with URL:', SUPABASE_URL);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});

// Test connection on initialization
supabase.auth.getSession().then(({ data, error }) => {
  if (error) {
    if (import.meta.env.DEV) {
      console.error('❌ Supabase connection test failed:', error.message);
    }
  } else {
    if (import.meta.env.DEV) {
      console.log('✅ Supabase client initialized successfully');
    }
  }
}).catch((error) => {
  if (import.meta.env.DEV) {
    console.error('❌ Failed to test Supabase connection:', error);
  }
});
